# This file was generated by GoReleaser. DO NOT EDIT.
class DynamodbToolkit < Formula
  desc "A command line toolkit for aws dynamodb"
  homepage "https://github.com/mingrammer/dynamodb-toolkit"
  url "https://github.com/mingrammer/dynamodb-toolkit/releases/download/v0.0.1/dynamodb-toolkit_0.0.1_darwin_amd64.tar.gz"
  version "0.0.1"
  sha256 "de37920340f5549f3dec9c7346b6a93b3170e6af0c6471ec659575554bac538a"

  def install
    bin.install "dynamotk"
  end

  test do
    system "#{bin}/dynamotk -v"
  end
end
