# This file was generated by GoReleaser. DO NOT EDIT.
class DynamodbToolkit < Formula
  desc "A command line toolkit for aws dynamodb"
  homepage "https://github.com/mingrammer/dynamodb-toolkit"
  url "https://github.com/mingrammer/dynamodb-toolkit/releases/download/v0.0.3/dynamodb-toolkit_0.0.3_darwin_amd64.tar.gz"
  version "0.0.3"
  sha256 "75e3d7182b956ecb08c4864b5354cf81d82613500b581a82d9eae89e6484f8bb"

  def install
    bin.install "dynamotk"
  end

  test do
    system "#{bin}/dynamotk -v"
  end
end
