# This file was generated by GoReleaser. DO NOT EDIT.
class DynamodbToolkit < Formula
  desc "A command line toolkit for aws dynamodb"
  homepage "https://github.com/mingrammer/dynamodb-toolkit"
  url "https://github.com/mingrammer/dynamodb-toolkit/releases/download/v0.0.2/dynamodb-toolkit_0.0.2_darwin_amd64.tar.gz"
  version "0.0.2"
  sha256 "082acd021bfe3e67ac45e781f38acbb881a40bfbbef168bb98d1f09beca7d6eb"

  def install
    bin.install "dynamotk"
  end

  test do
    system "#{bin}/dynamotk -v"
  end
end
